<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>$(PluginTargetFramework)</TargetFramework>
    <RootNamespace>Jellyfin.Plugin.Seerr.Tests</RootNamespace>
    <IsPackable>false</IsPackable>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <NoWarn>$(NoWarn);CA2007;xUnit1030</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Jellyfin.Model" Version="$(JellyfinVersion)" />
    <PackageReference Include="Jellyfin.Data" Version="$(JellyfinVersion)" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />
    <PackageReference Include="xunit" Version="2.9.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Jellyfin.Plugin.Seerr\Jellyfin.Plugin.Seerr.csproj" />
    <ProjectReference Include="..\jellyfin\src\Jellyfin.Database\Jellyfin.Database.Implementations\Jellyfin.Database.Implementations.csproj" />
  </ItemGroup>

</Project>
